### ISSUE TITLE
Units do not conform to SI, IEC standards

### ISSUE THREAD

**Issue by mvasilkov** [hustcc/filesize.js#1]
From [Wikipedia](https://en.wikipedia.org/wiki/Units_of_information):
<img width="345" alt="Multiples of bytes" src="https://user-images.githubusercontent.com/140257/61067087-753e6980-a40f-11e9-899f-91ac82bd025f.png">

Note that:

* Bytes are capital B
* In SI, kilobyte is kB (lowercase k)

So it should be along the lines of:

* SI: `['B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']`
* IEC: `['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB']`
* JEDEC: `['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']`

**Comment by hustcc** [comment]
You are right, can help me give me a pr?

**Comment by hustcc** [comment]
https://github.com/hustcc/filesize.js/commit/09ed44a49602f8c00a351f85382e88e46a1895d6

**Comment by workmanw** [comment]
@hustcc Has this change been released to NPM? The latest version (v2.0.0) still uses lowercase `b`.

**Comment by mvasilkov** [comment]
@workmanw I ended up updating / using this instead: https://github.com/mvasilkov/human-readable

**Comment by workmanw** [comment]
@mvasilkov Thanks for the quick response!
